Fatal error: exception Failure("main: expecting '2' arguments in 'foo(42, true, false)'")
